CREATE TABLE Authors (
  ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  name VARCHAR(50) NOT NULL
);

CREATE TABLE Books (
  ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  ISBN DECIMAL(13, 0) NOT NULL UNIQUE,
  title VARCHAR(100, 0) NOT NULL,
  cover VARCHAR(400, 0)
);

CREATE TABLE Books_Authors (
  ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  books_id INTEGER,
  authors_id INTEGER,
  num INTEGER
);